version: 2.1

parameters:
  docker_version:
    type: string
    default: 20.10.7
jobs:
  lint:
    docker:
      - image: cimg/base:2022.01-20.04
    steps:
      - checkout
      - setup_remote_docker
      - run: make lint

workflows:
  lint-test-deploy:
    jobs:
      - lint
      # - test:
      # - deploy:
