version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.01-20.04
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
